swagger: "2.0"
info:
  description: "Haversine API by 7x"
  version: "1 "
  title: "Distance API"
  termsOfService: "https://7x.ax/terms"
  contact:
    email: "support@7x.ax"
host: "api.7x.ax"
basePath: "/distance/v1"
schemes:
  - "https"
  - "http"
paths:
  /bycoordinates/{coordinates}:
    get:
      tags:
        - "distance"
      summary: "Get the great-circle distance between 2 pairs of co-ordinates."
      description: "Returns distance in either kilometres or miles."
      operationId: "getDistanceByCoordinates"
      produces:
        - "application/json"
      parameters:
        - name: "coordinates"
          in: "path"
          description: "Comma separated co-ordinates in the order of fromLatitude,fromLongitude,toLatitude,toLongitude."
          required: true
          type: "string"
          format: "utf8"
        - name: "unit"
          in: "query"
          description: "Unit of distance. 'km' for kilometres and 'mi' for miles."
          required: false
          default: "km"
          type: "string"
          format: "utf8"
        - name: "apikey"
          in: "query"
          description: "Your 7x API Key. Get it from https://app.7x.ax for free."
          required: true
          type: "string"
          format: "utf8"
      responses:
        "200":
          description: "Distance Calculated."
        "400":
          description: "Invalid Co-ordinates."
  /byaddress/{from}/{to}:
    get:
      tags:
        - "distance"
      summary: "Get the great-circle distance between 2 addresses."
      description: "Returns distance in either kilometres or miles."
      operationId: "getDistanceByCoordinates"
      produces:
        - "application/json"
      parameters:
        - name: "from"
          in: "path"
          description: "The first address. Example: Trafalgar Square, London, UK."
          required: true
          type: "string"
          format: "utf8"
        - name: "from"
          in: "path"
          description: "The second address. Example: Tower Bridge, London, UK."
          required: true
          type: "string"
          format: "utf8"
        - name: "unit"
          in: "query"
          description: "Unit of distance. 'km' for kilometres and 'mi' for miles."
          required: false
          default: "km"
          type: "string"
          format: "utf8"
        - name: "apikey"
          in: "query"
          description: "Your 7x API Key. Get it from https://app.7x.ax for free."
          required: true
          type: "string"
          format: "utf8"
      responses:
        "200":
          description: "Distance Calculated."
        "400":
          description: "Invalid Co-ordinates."

externalDocs:
  description: "Find out more about 7x APIs"
  url: "https://7x.ax"