import {Container} from '@/components/Container'
import Image from "next/future/image";
import backgroundImage from '@/images/background-faqs.jpg'


export function Terms() {
    return (
        <section
            id="terms"
            aria-labelledby="faq-title"
            className="relative overflow-hidden bg-slate-50 py-20 sm:py-32"
        >
            <Image
                className="absolute top-0 left-1/2 max-w-none translate-x-[-30%] -translate-y-1/4"
                src={backgroundImage}
                alt=""
                width={1558}
                height={946}
                unoptimized
            />
            <Container className="relative">
                <div className="mx-auto max-w-2xl lg:mx-0">
                    <h2
                        id="terms-title"
                        className="font-display text-3xl tracking-tight text-slate-900 sm:text-4xl"
                    >
                        Terms and Conditions of Use
                    </h2>
                </div>
                <div>
                    <p className="mt-4 text-lg tracking-tight text-slate-700">
                    </p><p className="mt-4 text-lg tracking-tight text-slate-700">Thank you for signing up for a
                    subscription with 7x (“7x”, “we” or “us”). By placing an order, clicking to accept this Agreement,
                    or using or accessing any 7x Service or related services, you agree to all the terms and conditions
                    of this Terms of Service Agreement (“Agreement”). If you are using an 7x Service or related services
                    on behalf of a company or other entity, then “Customer” or “you” means that entity, and you are
                    binding that entity to this Agreement. You represent and warrant that you have the legal power and
                    authority to enter into this Agreement and that, if the Customer is an entity, this Agreement and
                    each Order Form is entered into by an employee or agent with all necessary authority to bind that
                    entity to this Agreement. Please note that we may modify this Agreement as further described in the
                    amendments section below, so you should make sure to check this page from time to time. This
                    Agreement includes any Order Forms and Service-Specific Terms (as defined below) as well as any
                    policies or exhibits linked to or referenced herein.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">This Agreement is effective as of August
                    31, 2022.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">1. OVERVIEW OF THE 7x PLATFORM.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">7x provides managed APIs as a service.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2. DEFINITIONS.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.1 “Extension” means integrations,
                    applications, and other add-ons that are used with the 7x Service.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.2 “Affiliate” means any entity which is
                    controlled by, in control of, or is under common control with a party to this Agreement, where
                    “control” means either the power to direct the management or affairs of the entity or ownership of
                    50% or more of the voting securities of the entity.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.3 “Aggregate/Anonymous Data” means: (i)
                    data generated by aggregating Customer Data with other data so that results are non-personally
                    identifiable with respect to Customer or its Visitors; and (ii) learnings, logs, and data regarding
                    use of the 7x Service.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.4 “Authorized Users” means Customer’s
                    employees and contractors (such as media agencies or marketing consultants) who are acting for
                    Customer’s benefit and on its behalf.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.5 “Confidential Information” means code,
                    inventions, know-how, product plans, inventions, and technical and financial information exchanged
                    under this Agreement, that is identified as confidential at the time of disclosure or should
                    reasonably be considered confidential based on the circumstances surrounding the disclosure and the
                    nature of the information disclosed.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.6 “Content” means text, images, videos
                    or other content for the Customer Property.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.7 “Customer Apps” means the applications
                    (such as for mobile device platforms) created by 7x.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.8 “Customer Data” means: (i) Content;
                    (ii) Submitted Data; (iii) Visitor Data; and (iv) any other Customer Data specified in
                    Service-Specific Terms.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.9 “Customer Property or Properties”
                    means: (i) Customer Sites; (ii) Customer Apps; or (iii) other types of platforms or properties (as
                    may be supported by 7x) specified in the applicable Order Form.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.10 “Customer Sites” means the web
                    domains managed by 7x on behalf of the Customer.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.11 “Documentation” means the end user
                    technical documentation created by 7x and provided with the 7x Service.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.12 “7x Code” means the code developed
                    and provided by 7x to Customer for use in connection with the 7x Service, which may include 7x’s
                    JavaScript code, SDK(s) and Extensions developed and provided by 7x.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.13 “7x Service” means the specific
                    software-as-a-service product(s) of 7x, including any related 7x Code and Documentation.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.14 “7x Technology” means the 7x Service,
                    any and all related or underlying documentation, technology, code, know-how, logos and templates
                    (including in any reports or output obtained from the 7x Service), anything delivered as part of
                    support or other services, and any updates, modifications or derivative works of any of the
                    foregoing, including as may incorporate any Feedback.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.15 “Order Form” means any 7x ordering
                    documentation or online sign-up or subscription flow that references this Agreement.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.16 “Regulated Data” means: (i) any
                    personally identifiable information (other than personal information about Authorized Users); (ii)
                    any patient, medical, or other protected or regulated health information; or (iii) any government
                    IDs, financial information (including bank account or payment card numbers), or any other
                    information subject to regulation or protection under specific laws or regulations.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.17 “Scope of Use” means the usage limits
                    or other scope of use descriptions for the 7x Service included in the applicable Order Form
                    (including descriptions of packages and features) or Documentation. These include any numerical
                    limits on Visitors or Authorized Users, descriptions of product feature levels, and names or
                    numerical limits for Customer Properties.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.18 “Service-Specific Terms” means the
                    additional or different terms and conditions (if any) specific to an 7x Service or other 7x
                    products, features, services or subscription plans.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.19 “Submitted Data” means data uploaded,
                    inputted or otherwise submitted by Customer to the 7x Service, including Third-Party Content.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.20 “Subscription Term” means the initial
                    term for the subscription to the applicable 7x Service, as specified on Customer’s Order Form(s),
                    and each subsequent renewal term (if any).

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.21 “Third-Party Content” means content,
                    data or other materials that which Visitors submit or which the Customer provides to the 7x Service
                    from its third-party data providers, including through Extensions used by Customer.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.22 “Third-Party Product” means any
                    applications, integrations, software, code, online services, systems, other products, and Extensions
                    not developed by 7x.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.23 “Virus” means a virus, Trojan horse,
                    or worm that is designed to harm, disrupt or interfere with computers, software or hardware and
                    detectable using commercially reasonable procedures.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.24 “Visitor” means any end user of a
                    Customer Property.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">2.25 “Visitor Data” means the data
                    concerning the characteristics and activities of Visitors on the Customer Properties collected for
                    Customer by the 7x Service, including data submitted by the Visitor and any data specified in the
                    Service-Specific Terms.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">Other terms are defined in other Sections
                    of this Agreement or in the relevant Service-Specific Terms, policies, or Exhibits.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">3. ACCOUNT REGISTRATION AND USE.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">Customer and its Authorized Users need to
                    register for an 7x account in order to place orders or to access or receive an 7x Service. Account
                    information must be accurate, current, and complete, and will be governed by 7x’s Privacy Policy.
                    Customer agrees to keep this information up-to-date so that 7x may send notices, statements, and
                    other information by email or through Customer’s account. Customer must ensure that any user IDs,
                    passwords, and other access credentials (such as API tokens) for the 7x Service are kept strictly
                    confidential and not shared with any unauthorized person. Customer will be responsible for any and
                    all actions taken using its and its users’ accounts, passwords or access credentials. Customer must
                    notify 7x immediately of any breach of security or unauthorized use of its account. Accounts are
                    granted to specific Customers and must not be shared with others.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">4. USE RIGHTS.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">4.1 Use of 7x Services. Subject to all the
                    terms and conditions of this Agreement, 7x grants Customer a worldwide, non-exclusive,
                    non-transferable, non-sublicensable right and license during the applicable Subscription Term to
                    access and use the 7x Service(s) designated on Customer’s Order Form solely for Customer’s internal
                    business purposes, but only in accordance with this Agreement (including without limitation any
                    applicable Service-Specific Terms), the Documentation, and all applicable Scope of Use descriptions.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">4.2 Use by Others. Customer may permit its
                    Authorized Users to use the 7x Service, provided their use is for Customer’s benefit only and
                    remains in compliance with this Agreement. Customer will be responsible and liable for all
                    Authorized Users’ use and access and their compliance with the terms and conditions of this
                    Agreement. Use by all Authorized Users in aggregate will count towards applicable Scope of Use
                    restrictions.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">4.3 General Restrictions. Customer must
                    not (and must not allow any third party to: (i) break or circumvent any security measures or rate
                    limits of the 7x Service; (ii) access the 7x Service for the purpose of building a competitive
                    product or service or copying its features or user interface; (iii) use the 7x Service for purposes
                    of product evaluation, benchmarking, or other comparative analysis intended for publication without
                    7x’s prior written consent; or (x) remove or obscure any proprietary or other notices contained in
                    the 7x Service.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">4.4 Beta Releases and Free Access
                    Subscriptions. 7x may provide Customer with an 7x Service for free or on a trial basis (a “Free
                    Access Subscriptions”) or with “alpha”, “beta”, or other early-stage 7x Services, 7x Code,
                    integrations, or features (“Beta Releases”), which are optional for Customer to use. This Section
                    will apply to any Free Access Subscriptions or Beta Releases (even if Beta Releases are provided for
                    a fee or counts towards Customer’s Scope of Use allocations) and supersedes any contrary provision
                    in this Agreement. 7x may use good faith efforts in its discretion to assist Customer with Free
                    Access Subscriptions or Beta Releases. Nevertheless, and without limiting the other disclaimers and
                    limitations in this Agreement, CUSTOMER AGREES THAT ANY FREE ACCESS SUBSCRIPTION OR BETA RELEASES
                    ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT ANY WARRANTY, SUPPORT, MAINTENANCE,
                    STORAGE, SLA, OR INDEMNITY OBLIGATIONS OF ANY KIND. WITH RESPECT TO BETA RELEASES, CUSTOMER FURTHER
                    ACKNOWLEDGES AND AGREES THAT BETA RELEASES MAY NOT BE COMPLETE OR FULLY FUNCTIONAL AND MAY CONTAIN
                    BUGS, ERRORS, OMISSIONS, AND OTHER PROBLEMS FOR WHICH 7x WILL NOT BE RESPONSIBLE. ACCORDINGLY, ANY
                    USE OF BETA RELEASES ARE AT CUSTOMER’S SOLE RISK. 7x makes no promises that future versions of Beta
                    Releases will be released or will be available under the same commercial or other terms. 7x may
                    terminate Customer’s right to use any Free Access Subscriptions or Beta Releases at any time for any
                    reason or no reason in 7x’s sole discretion, without liability.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">5. CUSTOMER DATA.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">5.1 Rights in Customer Data. As between
                    the parties, Customer retains all right, title, and interest (including any intellectual property
                    rights) in and to the Customer Data and all content contained within the Customer Properties
                    (excluding any 7x Technology). Customer hereby grants 7x a non-exclusive, worldwide, royalty-free
                    right and license to collect, use, copy, store, transmit, modify, and create derivative works of the
                    Customer Data solely to the extent necessary to provide the 7x Service and related services to
                    Customer and as set out in Section 5.2 (Aggregate/Anonymous Data). For Content, this includes the
                    right to publicly display and perform Content and the Customer Properties (including derivative
                    works and modifications) as directed by Customer through the 7x Service.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">5.2 Aggregate/Anonymous Data. Customer
                    agrees that 7x will have the right to generate Aggregate/Anonymous Data and that Aggregate/Anonymous
                    Data is 7x Technology, which 7x may use for any business purpose during or after the term of this
                    Agreement (including without limitation to develop and improve 7x’s products and services and to
                    create and distribute reports and other materials). For clarity, 7x will only disclose
                    Aggregate/Anonymous Data externally in a de-identified (anonymous) form that does not identify
                    Customer, Authorized Users, or Visitors, and that is stripped of all persistent identifiers (such as
                    device identifiers, IP addresses, and cookie IDs). Customer is not responsible for 7x’s use of
                    Aggregate/Anonymous Data.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">5.3 Security. 7x agrees to maintain
                    commercially reasonable technical and organizational measures designed to secure its systems from
                    unauthorized disclosure and modification. 7x’s security measures will include: (i) storing Customer
                    Data on servers located in a physically secured location; and (ii) using firewalls, access controls,
                    and similar security technology designed to protect Customer Data from unauthorized disclosure and
                    modification.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">5.4 Data Export. 7x provides the ability
                    for Customer to export data at any time in the 7x Service as described in the Documentation.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">6. CUSTOMER OBLIGATIONS.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">Customer agrees to: (i) maintain a
                    legally-adequate privacy policy on its Customer Properties and provide all required disclosures to
                    its Visitors; (ii) use the 7x Service in compliance with 7x’s then-current Acceptable Use Policy;
                    (iii) comply with any third-party terms applicable to any Customer Apps (such as app store terms),
                    and to any Third-Party Products used in connection with the 7x Service; (iv) not take any action
                    that would cause 7x, the 7x Service or the 7x Code to become subject to any third-party terms
                    (including open source license terms). Customer represents and warrants that its Customer Properties
                    and the collection, use, and disclosure of Customer Data will not violate any third-party rights,
                    including intellectual property, privacy and publicity rights. If Customer receives any take down
                    requests or infringement notices related to Customer Data or its use of Third-Party Products, it
                    must promptly: (a) stop using the related item with the 7x Service; and (b) notify 7x. If 7x
                    receives any take down requests or infringement notices related to Customer Data or Customer’s use
                    of Third-Party Products, 7x may respond in accordance with its policies, and will notify and consult
                    with the Customer on next steps.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">7. SERVICES.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">7x makes available web-based support
                    through its website Additional support services may be available to Customer upon payment of
                    applicable fees (if any), as specified in Customer’s Order Form. Any support services are subject to
                    this Agreement and 7x’s applicable support policies. 7x may also provide onboarding, deployment and
                    other services under this Agreement. The scope, pricing, and other terms for these additional
                    services will be specified in an Order Form, Order Form exhibit, or other document referencing this
                    Agreement. Customer may use anything delivered as part of these additional services internally
                    during its Subscription Term to support its authorized use of the 7x Service, subject to the
                    restrictions in Section 4 (Use Rights) above applicable to the 7x Service itself. 7x’s ability to
                    deliver services will depend on Customer’s reasonable and timely cooperation and the accuracy and
                    completeness of any information from Customer needed to deliver the services. For avoidance of
                    doubt, Customer retains ownership of any Confidential Information it provides to 7x.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">8. FEES AND PAYMENT.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">Customer agrees to pay all fees in the
                    currency and payment period specified in the applicable Order Form. 7x’s fees are exclusive of all
                    taxes, and Customer must pay any applicable sales, use, VAT, GST, excise, withholding, or similar
                    taxes or levies, whether domestic or foreign, other than taxes based on the income of 7x. Customer
                    will make tax payments to 7x to the extent amounts are appropriately included in 7x’s invoices. 7x
                    sends invoices electronically, and invoices for the 7x Service in advance as set out in the Order
                    Form, and for overages, if applicable in the relevant Order Form, monthly in arrears. If Customer
                    requires a Purchase Order number referenced on 7x’s invoice, Customer must promptly provide the
                    Purchase Order number. If Customer does not promptly provide the Purchase Order number, Customer
                    agrees to pay the invoice without a referenced Purchase Order Number. Some customers may have the
                    option to pay by credit card. If Customer is paying by credit card, it authorizes 7x to charge and
                    fees other amounts automatically to Customer’s credit card without invoice. Payments are
                    non-refundable and non-creditable and payment obligations non-cancellable. Late payments may be
                    subject to a service charge equal to the lesser of 3% per month of the amount due or the maximum
                    amount allowed by law.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">9. TERM AND TERMINATION.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">9.1 Term. This Agreement is effective
                    until all Subscription Terms for the 7x Service(s) have expired or are terminated as expressly
                    permitted in this Agreement.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">9.2 Subscription Term and Renewals. By
                    executing an Order Form for purchase of an 7x Service, Customer is agreeing to pay applicable fees
                    for the entire Subscription Term. Customer cannot cancel or terminate a Subscription Term except as
                    expressly permitted by Section 9.4 (Termination for Cause) or a Service-Specific Term. If no
                    subscription start date is specified on the applicable Order Form, the subscription starts when
                    Customer first obtains access to the 7x Service. Each Subscription Term will automatically renew for
                    additional successive monthly periods unless: (i) otherwise stated on the applicable Order Form; or
                    (ii) either party gives written notice of non-renewal at least thirty (30) days before the end of
                    the then-current Subscription Term. Pricing for any Subscription Term renewal, new Order Form, or
                    Order Form changes will be at 7x’s then-applicable rates.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">9.3 Suspension of Service. 7x may suspend
                    Customer’s access to the 7x Service(s) if: (i) Customer’s account is overdue; or (ii) Customer has
                    exceeded its Scope of Use limits. 7x may also suspend Customer’s access to the 7x Service(s), remove
                    Customer Data or disable Third-Party Products if it determines that: (a) Customer has breached
                    Sections 4 (Use Rights) or 6 (Customer Obligations); or (b) suspension is necessary to prevent harm
                    or liability to other customers or third parties, or to preserve the security, stability,
                    availability or integrity of the 7x Service. 7x will have no liability for taking action as
                    permitted above. For the avoidance of doubt, Customer will remain responsible for payment of fees
                    during any suspension period under this Section 9.3. However, unless this Agreement has been
                    terminated, 7x will cooperate with Customer to promptly restore access to the 7x Service once it
                    verifies that Customer has resolved the condition requiring suspension.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">9.4 Termination for Cause. Either party
                    may terminate this Agreement, including any related Order Form, if the other party: (i) fails to
                    cure any material breach of this Agreement (including a failure to pay undisputed fees) within
                    thirty (30) days after written notice detailing the breach; (ii) ceases operation without a
                    successor; or (iii) if permitted by applicable law, seeks protection under any bankruptcy,
                    receivership, trust deed, creditors’ arrangement, composition, or comparable proceeding, or if any
                    of these proceedings are instituted against that party (and not dismissed within sixty (60) days
                    thereafter). 7x may also terminate this Agreement or any related Order Forms immediately if Customer
                    breaches Sections 4 (Use Rights) or 6 (Customer Obligations), or for repeated violations of this
                    Agreement.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">9.5 Effect of Termination. Upon any
                    expiration or termination of this Agreement or an Order Form: (i) Customer’s license rights
                    terminate and it must promptly: (a) stop use of the applicable 7x Service(s) (including any related
                    7x Technology); and (b) delete (or, at 7x’s request, return) any and all copies of the 7x Code, any
                    7x documentation, passwords or access codes, and any other 7x Confidential Information in Customer’s
                    possession, custody, or control; and (ii) Customer’s right to access any Customer Data in the
                    applicable 7x Service will cease and 7x may delete the Customer Data at any time after 30 days from
                    the date of termination. If 7x terminates this Agreement for cause as provided in Section 9.4
                    (Termination for Cause), any payments for the remaining portion of the Subscription Term will become
                    due and must be paid immediately by Customer. Except where this Agreement specifies an exclusive
                    remedy, all remedies under this Agreement, including termination or suspension, are cumulative and
                    not exclusive of any other rights or remedies that may be available to a party.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">9.6 Survival. The following Sections
                    survive any expiration or termination of this Agreement: 2 (Definitions); 3 (Account Registration
                    and Use); 4.3 (General Restrictions); 4.4 (Beta Releases and Free Access Subscriptions); 5.1 (Rights
                    in Customer Data); 5.2 (Aggregate/Anonymous Data); 8 (Fees and Payment); 9 (Term and Termination);
                    10 (Confidential Information); 11 (7x Technology); 12 (Indemnification); 13.2 (Disclaimers); 14
                    (Limitations of Liability); 15 (Third-Party Products and Integrations); and 16 (General).

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">10. CONFIDENTIAL INFORMATION.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">10.1 Confidentiality Obligation. Each
                    party (as the receiving party) must: (i) hold in confidence and not disclose the other party’s
                    Confidential Information to third parties except as permitted by this Agreement; and (ii) only use
                    the other party’s Confidential Information to fulfill its obligations and exercise its rights under
                    this Agreement. Each party may share the other party’s Confidential Information with its, and its
                    Affiliates’, employees, agents or contractors having a legitimate need to know (which, for 7x,
                    includes the subcontractors referenced in Section 16.5), provided that the party remains responsible
                    for any recipient’s compliance with the terms of this Section 10 and that these recipients are bound
                    to confidentiality obligations no less protective than this Section.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">10.2 Exclusions. These confidentiality
                    obligations do not apply to (and Confidential Information does not include) information that: (i) is
                    or becomes public knowledge through no fault of the receiving party; (ii) was known by the receiving
                    party before it received the Confidential Information; (iii) is rightfully obtained by the receiving
                    party from a third party without breach of any confidentiality obligation; or (iv) is independently
                    developed by the receiving party without using the disclosing party’s Confidential Information. A
                    party may also disclose the other party’s Confidential Information to the extent required by law or
                    court order, provided it gives advanced notice (if permitted by law) and cooperates in any effort by
                    the other party to obtain confidential treatment for the information.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">10.3 Remedies. The parties acknowledge
                    that disclosing Confidential Information may cause substantial harm for which damages alone may be
                    an insufficient remedy, and so on breach of this Section, each party is entitled to seek appropriate
                    equitable relief in addition to any other remedies it may have at law.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">11. 7x TECHNOLOGY.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">11.1 Ownership and Updates. This is a
                    subscription agreement for access to and use of the 7x Service. Customer acknowledges that it is
                    obtaining only a limited right to use the 7x Service and that irrespective of any use of the words
                    “purchase”, “sale” or similar terms, no ownership rights are transferred to Customer under this
                    Agreement. Customer agrees that 7x (or its suppliers) retain all rights, title and interest
                    (including all intellectual property rights) in and to all 7x Technology (which is deemed 7x’s
                    Confidential Information) and reserves any licenses not specifically granted in this Agreement.
                    Other than the 7x Code, the 7x Service is offered as an online, hosted product. Accordingly,
                    Customer acknowledges and agrees that it has no right to obtain a copy of the software behind any 7x
                    Service and that 7x at its option may make updates, bug fixes, modifications or improvements to the
                    7x Service from time-to-time.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">11.2 Feedback. If Customer elects to
                    provide any suggestions, comments, improvements, information, ideas or other feedback or related
                    materials to 7x (collectively, “Feedback”), Customer hereby grants 7x a worldwide, perpetual,
                    non-revocable, sublicensable, royalty-free right and license to use, copy, disclose, license,
                    distribute, and exploit any Feedback in any format and in any manner without any obligation,
                    payment, or restriction based on intellectual property rights or otherwise, however 7x will not
                    identify Customer as the source of the Feedback. Nothing in this Agreement limits 7x’s right to
                    independently use, develop, evaluate, or market products, whether incorporating Feedback or
                    otherwise.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">12. INDEMNIFICATION.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">Customer agrees to defend and indemnify 7x
                    from and against any third-party claims and liabilities to the extent resulting from: Customer Data;
                    Customer Properties (including services or products provided through the Customer Properties); or a
                    breach or alleged breach of Section 6 (Customer Obligations). Customer must not settle any claim
                    without 7x’s prior written consent if the settlement would require 7x to admit fault, pay amounts
                    that Customer must pay under this Agreement, or take or refrain from taking any action. 7x may
                    participate in a claim through counsel of its own choosing at its own expense and Customer and 7x
                    will reasonably cooperate on the defense.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">13. DISCLAIMERS.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">ALL 7x TECHNOLOGY AND RELATED SERVICES ARE
                    PROVIDED “AS IS” AND ON AN “AS AVAILABLE” BASIS. NEITHER 7x NOR ITS SUPPLIERS MAKE ANY WARRANTIES,
                    EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
                    MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT. 7x MAKES NO
                    REPRESENTATION, WARRANTY OR GUARANTEE THAT 7x TECHNOLOGY WILL MEET CUSTOMER’S REQUIREMENTS OR
                    EXPECTATIONS, THAT CUSTOMER DATA WILL BE ACCURATE, COMPLETE, OR PRESERVED WITHOUT LOSS, OR THAT 7x
                    TECHNOLOGY WILL BE TIMELY, UNINTERRUPTED OR ERROR-FREE. 7x DOES NOT GUARANTEE THAT SECURITY MEASURES
                    WILL BE ERROR-FREE AND WILL NOT BE RESPONSIBLE OR LIABLE FOR UNAUTHORIZED ACCESS BEYOND ITS
                    REASONABLE CONTROL. 7x WILL NOT BE RESPONSIBLE OR LIABLE IN ANY MANNER FOR ANY CUSTOMER PROPERTIES,
                    THIRD-PARTY PRODUCTS, THIRD-PARTY CONTENT, OR NON-7x SERVICES (INCLUDING FOR ANY DELAYS,
                    INTERRUPTIONS, TRANSMISSION ERRORS, SECURITY FAILURES, AND OTHER PROBLEMS CAUSED BY THESE ITEMS),
                    FOR REGULATED DATA RECEIVED FROM CUSTOMER IN BREACH OF THIS AGREEMENT, FOR THE COLLECTION, USE AND
                    DISCLOSURE OF CUSTOMER DATA AUTHORIZED BY THIS AGREEMENT, OR FOR DECISIONS OR ACTIONS TAKEN (OR NOT
                    TAKEN) BY CUSTOMER BASED UPON 7x TECHNOLOGY OR 7x’S RELATED SERVICES (INCLUDING CHANGES TO CUSTOMER
                    PROPERTIES). THE DISCLAIMERS IN THIS SECTION WILL APPLY TO THE MAXIMUM EXTENT PERMITTED BY
                    APPLICABLE LAW, NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THIS AGREEMENT. CUSTOMER MAY HAVE OTHER
                    STATUTORY RIGHTS. HOWEVER, ANY STATUTORILY REQUIRED WARRANTIES UNDER APPLICABLE LAW, IF ANY, WILL BE
                    LIMITED TO THE SHORTEST PERIOD AND MAXIMUM EXTENT PERMITTED BY LAW.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">14. LIMITATIONS OF LIABILITY.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">14.1 Liability Cap. TO THE MAXIMUM EXTENT
                    PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL 7x OR ITS SUPPLIERS BE LIABLE FOR ANY LOSS OF USE,
                    LOST OR INACCURATE DATA, INTERRUPTION OF BUSINESS, LOST PROFITS, COSTS OF DELAY, REPUTATIONAL HARM,
                    OR ANY INDIRECT, SPECIAL, INCIDENTAL, COVER, RELIANCE OR CONSEQUENTIAL DAMAGES OF ANY KIND HOWEVER
                    CAUSED, EVEN IF INFORMED IN ADVANCE OF THE POSSIBILITY OF THESE DAMAGES. 7x’S AND ITS SUPPLIERS’
                    TOTAL LIABILITY WILL NOT EXCEED IN AGGREGATE THE AMOUNT ACTUALLY PAID OR PAYABLE BY CUSTOMER TO 7x
                    FOR THE APPLICABLE 7x SERVICE OR RELATED SERVICES IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM. FOR
                    FREE ACCESS SUBSCRIPTIONS OR BETA RELEASES, 7x’S TOTAL LIABILITY WILL NOT EXCEED IN AGGREGATE FIFTY
                    U.S. DOLLARS ($50 US).

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">14.2 Exceptions. NOTWITHSTANDING THE
                    FOREGOING, NONE OF THE LIMITATIONS IN THIS SECTION 14 EXCLUDES EITHER PARTY’S LIABILITY FOR FRAUD OR
                    FOR DEATH OR PERSONAL INJURY TO THE EXTENT CAUSED BY A PARTY’S NEGLIGENCE. IN ADDITION, THE LAWS IN
                    SOME JURISDICTIONS MAY NOT ALLOW SOME OF THE LIMITATIONS OF LIABILITY IN THIS SECTION. IF ANY OF
                    THESE LAWS IS FOUND TO APPLY TO THIS AGREEMENT, THIS SECTION 14 WILL APPLY TO THE MAXIMUM EXTENT
                    PERMITTED BY LAW.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">14.3 Failure of Essential Purpose. EACH
                    PARTY ACKNOWLEDGES AND AGREES THAT THIS SECTION 14 IS A FUNDAMENTAL BASIS OF THE BARGAIN AND A
                    REASONABLE ALLOCATION OF RISK BETWEEN THE PARTIES AND WILL SURVIVE AND APPLY TO ANY CLAIMS ARISING
                    OUT OF OR RELATED TO THIS AGREEMENT, ANY 7x TECHNOLOGY OR ANY RELATED SERVICES, REGARDLESS OF THE
                    THEORY OF LIABILITY (CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE), EVEN IF ANY LIMITED REMEDY IN
                    THIS AGREEMENT IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">15. THIRD-PARTY PRODUCTS AND INTEGRATIONS.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">If Customer uses Third-Party Products in
                    connection with the 7x Services, those products may make Third-Party Content available to Customer
                    and may access Customer’s instance of the 7x Service, including Customer Data. 7x does not warrant
                    or support Third-Party Products or Third-Party Content (whether or not these items are designated by
                    7x as “powered”, “verified” or otherwise) and disclaims all responsibility and liability for these
                    items and their access to the 7x Services, including their modification, deletion, disclosure, or
                    collection of Customer Data. 7x is not responsible in any way for Customer Data once it is
                    transmitted, copied, or removed from the 7x Services by Customer or under Customer’s direction.
                    Customer may use 7x’s Extensions to enable non-7x Extensions for use with the 7x Services.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16. GENERAL.
                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.1 Assignment. This Agreement will bind
                    and inure to the benefit of each party’s permitted successors and assigns. Neither party may assign
                    this Agreement without the advance written consent of the other party, except that 7x may assign
                    this Agreement without consent to an Affiliate or in connection with a merger, reorganization,
                    acquisition, or other transfer of all or substantially all of its assets or voting securities. Any
                    attempt to transfer or assign this Agreement except as expressly authorized under this Section 16.1
                    will be void.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.2 Notices. Any notice or communication
                    under this Agreement must be in writing. Customer must send any notices under this Agreement
                    (including breach notices) to 7x, in English, at the following address, legal@7x.net, and include
                    “Attn. Legal Department” in the subject line. 7x may send notices to the email addresses on
                    Customer’s account or, at 7x’s option, to Customer’s last-known postal address. 7x may also provide
                    operational notices regarding the 7x Service or other business-related notices through conspicuous
                    posting of the notice on 7x’s website or the 7x Service. Each party consents to receiving electronic
                    notices. 7x is not responsible for any automatic filtering Customer or its network provider may
                    apply to email notifications.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.3 Publicity. 7x may not use Customer’s
                    name, logo, and marks for its marketing purposes unless otherwise specified in the applicable Order
                    Form or with Customer’s prior written permission.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.4 Subcontractors. 7x may use
                    subcontractors and permit them to exercise the rights granted to 7x in order to provide the 7x
                    Service and related services under this Agreement. These subcontractors may include, for example,
                    7x’s hosted service and CDN providers. However, subject to all terms and conditions of this
                    Agreement, 7x will remain responsible for: (i) compliance of its subcontractors with the terms of
                    this Agreement; and (ii) the overall performance of the 7x Services if and as required under this
                    Agreement.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.5 Subpoenas. Nothing in this Agreement
                    prevents 7x from disclosing Customer Data to the extent required by law, subpoenas, or court orders,
                    but 7x will use commercially reasonable efforts to notify Customer where permitted to do so.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.6 Independent Contractors. The parties
                    to this Agreement are independent contractors, and this Agreement does not create a partnership,
                    joint venture, employment, franchise, or agency relationship. Neither party has the power to bind
                    the other or incur obligations on the other party’s behalf without the other party’s prior written
                    consent.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.7 Force Majeure. Neither party will be
                    liable for any delay or failure to perform its obligation under this Agreement (except payment
                    obligations) if the delay or failure is due to causes beyond its reasonable control, such as a
                    strike, blockade, war, act of terrorism, riot, natural disaster, failure or reduction of power or
                    telecommunications or data networks or services, or government act.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.8 Export. Customer is responsible for
                    obtaining any required export or import authorizations for use of the 7x Services. Customer
                    represents and warrants that it, its Affiliates, and its Authorized Users are not on any U.S.
                    government list of prohibited or restricted parties or located in (or a national of) a country
                    subject to a U.S. government embargo or that has been designated by the U.S. government as a
                    “terrorist supporting” country. Customer must not access or use the 7x Service in violation of any
                    U.S. export embargo, prohibition or restriction.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.9 Amendments; Waivers. Any modification
                    or amendment to this Agreement must be made in writing and executed by an authorized representative
                    of each party. However, if 7x modifies the Agreement or any applicable Service-Specific Terms during
                    Customer’s Subscription Term, the modified version will take effect upon Customer’s next
                    Subscription Term renewal. In addition: (a) If 7x launches new products or optional features that
                    require opt-in acceptance of new terms, those terms will apply upon Customer’s acceptance or use;
                    (b) changes to any terms will take effect immediately for Free Access Subscriptions; and (c) during
                    a Subscription Term, 7x may update 7x’s Security page, Privacy Policy, and Acceptable Use Policy
                    from time-to-time to reflect process improvements or changing practices, and these changes will take
                    effect thirty (30) days from the date of posting so long as they do not substantially diminish
                    Customer’s rights or create substantial additional Customer obligations during a Subscription Term.
                    7x’s Documentation is available online and constantly being developed and improved, and as a result,
                    during a Subscription Term 7x may update the Documentation to reflect best practice with the
                    relevant 7x Service, provided that these changes do not substantially diminish Customer’s rights or
                    create substantial Customer obligations. In the event of any conflict between this Agreement and any
                    Order Form, this Agreement will take precedence unless otherwise expressly provided. No waiver will
                    be implied from conduct or failure to enforce or exercise rights under this Agreement. Waivers must
                    be made in writing and executed by an authorized representative of the waiving party.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.10 Severability. If any provision of
                    this Agreement is found by any court of competent jurisdiction to be unenforceable or invalid, that
                    provision will be limited to the minimum extent necessary so that this Agreement may otherwise
                    remain in effect.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.11 No Third-Party Rights. Nothing in
                    this Agreement confers on any third party the right to enforce any provision of this Agreement.
                    Customer acknowledges that each Order Form only permits use by and for the legal entity or entities
                    identified in the Order Form(s) as the Customer, and not any Customer Affiliates.

                </p><p className="mt-4 text-lg tracking-tight text-slate-700">16.12 Entire Agreement. This Agreement
                    represents the parties’ complete and exclusive understanding relating to the Agreement’s subject
                    matter. It supersedes all prior or contemporaneous oral or written communications, proposals and
                    representations with respect to the 7x Technology or any other subject matter covered by this
                    Agreement. The terms of the United Nations Convention on Contracts for the Sale of Goods do not
                    apply to this Agreement. Any terms provided by Customer (including as part of any purchase order or
                    other business form used by Customer) are for administrative purposes only, and have no legal
                    effect.

                </p>

                </div>
            </Container>
        </section>
    )
}
