openapi: 3.0.1
info:
  title: Timezone API
  description: Timezone API by 7x
  termsOfService: https://7x.ax/terms-and-conditions
  contact:
    email: support@7x.ax
  version: v1
externalDocs:
  description: Find out more about 7x APIs
  url: http://7x.ax
servers:
  - url: https://api.7x.ax/timezone/v1
  - url: http://api.7x.ax/timezone/v1
paths:
  /bycoordinates/{coordinates}:
    get:
      tags:
        - timezone
      summary: Get applicable timezones for a pair of co-ordinates
      description: Returns latitude, longitude and timezone
      operationId: getTimezone
      parameters:
        - name: coordinates
          in: path
          description: Comma separated co-ordinates in the order of latitude,longitude
          example: 24.54940,45.58403
          required: true
          schema:
            type: string
            format: utf8
        - name: apikey
          in: query
          description: Your 7x API Key. Get it from https://app.7x.ax for free.
          required: true
          schema:
            type: string
            format: utf8
      responses:
        200:
          description: Returns an array of applicable Timezones.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: The HTTP code.
                    example: 200
                  status:
                    type: string
                    description: The HTTP status.
                    example: "OK"
                  data:
                    type: object
                    properties:
                      latitude:
                        type: number
                        description: The latitude.
                        example: 25.2048
                      longitude:
                        type: number
                        description: The longitude.
                        example: 55.2708
                      timezone:
                        type: array
                        description: An array of timezones.
                        items:
                          type: string
                          example: Asia/Dubai

        400:
          description: Invalid Co-ordinates.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: The HTTP code.
                    example: 400
                  status:
                    type: string
                    description: The HTTP status.
                    example: "Bad Request."
                  data:
                    type: string
                    example: Invalid Co-ordinates.
components: {}
